name: CodeCov
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.10'
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: '3.10'
      - name: 'generate report'
        env:
          API_KEY: ${{ secrets.COV_API_KEY }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          coverage run -m pytest
      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          flags: pytest
          fail_ci_if_error: false
